### ISSUE TITLE
Roadmap - Markdown

### ISSUE THREAD

**Issue by d21emijo** [HGustavs/LenaSYS#13846]
# Roadmap for all the markdown

All things markdown and preview

## Markdown
- [ ] if we have a preview html or preview png this should be shown as the preview content. 
#13698
- [ ] Additional github markdown features. 
#13195

## Preview
- [ ] Interface buttons for markdown preview 
#13198
