### ISSUE TITLE
Roadmap - Github integration

### ISSUE THREAD

**Issue by d21emijo** [HGustavs/LenaSYS#13845]
# Roadmap For all Github functions

The Github integration roadmap is for how the fetched data from Github and put into the sqlite db is being used.

![image](https://user-images.githubusercontent.com/102797583/236827312-d29d1423-79be-4102-aa4f-fd2f330df86c.png)

one should be able to use the Github icon and choose a dir in the Github repo to get all the codeexamples... tbc 

##  Order of operation
- [x] Investigate use of subfolders for github examples in file editor 
#13511
- [x] Make refresh button run the download script 
#13943 
- [x] Github Folder Structure for Github Integration 
#12951
- [x] Connect the github button in moment with ability to generate examples 
#13897
- [x] Code examples should automatically be created and named after the files in the folder 
#13549
- [x] The refresh button on moment type needs a URL to function 
#13456
- [x] Code example New Github File 
#13879
- [x] Moments should automatically be created and named after the directories in the github folder 
#13690
- [x] .md or .txt .index file that we can use to control the ordering of code examples 
#13016
- [x] New code example should not affect existing order of code examples 
#13017

##  Handling of code examples from github

Created from: #13875, #13877, #13879, #13880  
###  If a code example comes from the github repo there is a certain locking behavior that is important
Reference case from Henrik: https://github.com/LenaSYS/Webbprogrammering-Examples/tree/master

Issues from Henrik:
- [x] It should be possible to hide the example in the course view
- [ ] It should be possible to reorder examples within a heading but not between headings
#13932
- [x] We should be able to rename examples in the course view at will.
#13933
- [ ] Code example locking for github files 
#13875
- [x] When a new example is added, it should be placed added at the bottom of the list. To then be manually reorder with the normal ordering operation. 
#13935
- [x] When an example is removed from github it should be hidden in the course view and not deleted
#13931
- [x] If a new file is added on github in a folder that is tracked by the synchronization module we want this file to be added automatically to the course view. (Might be broken down)
#13934
- [x] New files should not be hidden by default, but be shown immediately after the first refresh (manual or automatic refresh).
#13936

##  Manual and automatic synchronization option 
Created from: #13880
- [x] Synchronization of github repo should run automatically if the course is "loaded"
#13987 
- [x] Oversaturate github if a user re-clicks the refresh button/buttons
#13999
- [x] Stop the user from sending to many api request under a short amount of time. 
#14012
- [ ] The automatic and manual synchronization options should have individual settings for each... for exampel by changing a line at the top of one of the files. No need to have this setting in the user interface.
#14002

## Stray issues for Github

- [x] Removing functionality to edit downloaded GitHub files 
#13821
- [x] Filtering buttons, manual and GitHub 
#13731
- [x] Update GitHub URL in edit course 
#13890
- [x] Add the downloaded files to the code examples 
#13072
- [ ] Next Code example in Code Viewer 
#13877
- [ ] Github Synchronization options 
#13880
- [x] Redesign of refresh button 
#13959
- [x] Index file to control which files or directories to be downloaded 
#13904
