### ISSUE TITLE
Roadmap - Sql

### ISSUE THREAD

**Issue by d21emijo** [HGustavs/LenaSYS#13858]
# Roadmap for the databases Sql and Sqlite

sql:

sqlite:

## Sql database / courses data /
- [ ] Change/update tables in MySQL db to use unique foreign keys. 
#13793
- [ ] When deleting a course we do not delete all the connected things to the course 
#13597
- [ ]  Course local files sharing the same names with GitHub files 
#13648
- [ ] Uppdatering från repot ska inte förstöra eller ta bort manuellt gjorda exempel och filer 
#13703

## Sqlite database /Github data
- [ ] SQLite integration in install.php to make sure that it is synced with MySQL 
#13774
- [ ] Remove files from SQLite if they are removed in file editor 
#13764
