### ISSUE TITLE
Requirements from customer yet to be fully completed

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#14250]
Github integration roadmap #12926 
- [ ] Code examples  should automatically be added to the courses by linking to a folder to a part of a course.
- [ ] We link to the main repository in some way for example https://github.com/HGustavs/Webbprogrammering-Examples/
- [ ] Code examples should automatically be created and named after the files in the folder
- [ ] If a .md with the same name as the code example exists this will be used as the description of that code example
- [ ] When code is updated to the folder in the repository the examples should be added/removed/updated accordingly based on file names etc

Github integration #12927 
- [ ] We do not want to number code examples (since we get problems if we want to make a new example between example 1 and 2)
- [ ] We want the order to remain when new examples are added to the folder 
- [ ] We need to make a mockup / test faces for some kind of integration with github such as a .md or .txt .index file that we can use to control the ordering of code examples from github by committing to that file
Was changed and solved as index file #13904
- [ ] We want support for other non-course-module example collections such as the curated example set in "complete examples" in https://dugga.iit.his.se/DuggaSys/sectioned.php?courseid=7&coursename=Webbprogrammering&coursevers=82518 
Start of this where done here #14021

Github integration of assignment texts as .md files #12931
- [ ] Currently assignment texts are stored in lenasys as files we want the same kind of github integration as we have for the code examples.

Additional github markdown features. #13195
- [ ] Started but not completed with issues #13195 and #13198

Interface buttons for markdown preview #13198
- [ ] #13198

Code example locking for github files #13875
- [ ] 1. It should be possible to hide the example in the course view (if we do not want to show all examples)
- [ ] 2. It should be possible to reorder examples within a heading but not between headings
#13932
- [ ] 3. When an example is removed from github it should be hidden in the course view and not deleted
- [ ] 4. We should be able to rename examples in the course view at will.

Next Code example in Code Viewer #13877
Was found that what was asked already worked so it resulted in this issue:
- [ ] Hidden code examples shouldn't be able to be accessed through the next and previous buttons #14052 

Github Synchronization options #13880
Almost done, one fix is left, which was left for demo.
- [ ] Timer for refresh button is not consistent #14241
